name: hello-world
on: 
  push
  
actions_need_to_pass: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "secondd job"


