name: hello-world
on: 
    push: {}
    workflow_job:
      types: [completed]
    workflow_run:
      types: [completed]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "secondd job"
